package com.timepath.steam.webapi;

/**
 *
 * @author TimePath
 */
public abstract class LoginDialog extends javax.swing.JDialog {

    /**
     * Creates new form LoginDialog
     * <p>
     * @param parent
     * @param modal
     */
    public LoginDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * @return the captchaInput
     */
    public javax.swing.JTextField getCaptchaInput() {
        return captchaInput;
    }

    /**
     * @return the captchaLabel
     */
    public javax.swing.JLabel getCaptchaLabel() {
        return captchaLabel;
    }

    /**
     * @return the loginButton
     */
    public javax.swing.JButton getLoginButton() {
        return loginButton;
    }

    /**
     * @return the messageLabel
     */
    public javax.swing.JLabel getMessageLabel() {
        return messageLabel;
    }

    /**
     * @return the passInput
     */
    public javax.swing.JPasswordField getPassInput() {
        return passInput;
    }

    /**
     * @return the steamguardInput
     */
    public javax.swing.JTextField getSteamguardInput() {
        return steamguardInput;
    }

    /**
     * @return the userInput
     */
    public javax.swing.JTextField getUserInput() {
        return userInput;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        userInput = new javax.swing.JTextField();
        passInput = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        steamguardInput = new javax.swing.JTextField();
        captchaPanel = new javax.swing.JPanel();
        captchaLabel = new javax.swing.JLabel();
        captchaInput = new javax.swing.JTextField();
        messageLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        userInput.setText("user");
        userInput.setMinimumSize(new java.awt.Dimension(120, 28));
        jPanel4.add(userInput);

        passInput.setText("pass");
        passInput.setMinimumSize(new java.awt.Dimension(120, 28));
        passInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login(evt);
            }
        });
        jPanel4.add(passInput);

        jPanel7.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("steamguard");
        jPanel1.add(jLabel1);

        steamguardInput.setMinimumSize(new java.awt.Dimension(120, 28));
        jPanel1.add(steamguardInput);

        jPanel7.add(jPanel1, java.awt.BorderLayout.CENTER);

        captchaPanel.setLayout(new javax.swing.BoxLayout(captchaPanel, javax.swing.BoxLayout.LINE_AXIS));

        captchaLabel.setText("captcha");
        captchaPanel.add(captchaLabel);

        captchaInput.setMinimumSize(new java.awt.Dimension(120, 28));
        captchaPanel.add(captchaInput);

        jPanel7.add(captchaPanel, java.awt.BorderLayout.SOUTH);

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        messageLabel.setText("message");
        jPanel6.add(messageLabel, java.awt.BorderLayout.CENTER);

        loginButton.setText("login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel6.add(loginButton, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login
        login();
    }//GEN-LAST:event_login

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        login();
    }//GEN-LAST:event_loginButtonActionPerformed

    public abstract void login();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginDialog dialog = new LoginDialog(new javax.swing.JFrame(), true) {

                    @Override
                    public void login() {

                    }

                };
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField captchaInput;
    private javax.swing.JLabel captchaLabel;
    private javax.swing.JPanel captchaPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPasswordField passInput;
    private javax.swing.JTextField steamguardInput;
    private javax.swing.JTextField userInput;
    // End of variables declaration//GEN-END:variables
}
